# Generated by Django 4.2.30 on 2026-08-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Time')),
                ('community_key', models.CharField(max_length=255, verbose_name='COMMUNITY KEY')),
                ('sponsor_key', models.CharField(max_length=255, verbose_name='SPONSOR KEY')),
                ('expired', models.DateTimeField(auto_now=True, null=True, verbose_name='Expired Time')),
            ],
            options={
                'verbose_name': 'bomiot AuthModel',
                'verbose_name_plural': 'bomiot AuthModel',
                'db_table': 'bomiot_authmodel',
                'ordering': ['-id'],
            },
        ),
    ]
