# Generated by Django 4.2.30 on 2026-08-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authmodel',
            name='expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expired Time'),
        ),
    ]
